// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EstLambSurv
Rcpp::List EstLambSurv(double s, int n, int nvar, const arma::ivec& k, int nk, const arma::vec& tau, const arma::vec& caltimes, const arma::vec& gaptimes, const arma::vec& censored, const arma::vec& intercepts, const arma::vec& slopes, const arma::vec& lastperrep, const arma::vec& perrepind, const arma::vec& effagebegin, const arma::vec& effage, int ndiseff, const arma::vec& diseff, const arma::mat& cov, double alpha, const arma::vec& beta, const arma::vec& Z, const arma::vec& offset, int rhoFunc, arma::vec& lambda, arma::vec& deltalambda, arma::vec& surv);
RcppExport SEXP _gcmrec_EstLambSurv(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP ndiseffSEXP, SEXP diseffSEXP, SEXP covSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP lambdaSEXP, SEXP deltalambdaSEXP, SEXP survSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< int >::type ndiseff(ndiseffSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type diseff(diseffSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type deltalambda(deltalambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type surv(survSEXP);
    rcpp_result_gen = Rcpp::wrap(EstLambSurv(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alpha, beta, Z, offset, rhoFunc, lambda, deltalambda, surv));
    return rcpp_result_gen;
END_RCPP
}
// EstimWithFrailty
void EstimWithFrailty(double s, int n, int nvar, arma::ivec k, int nk, arma::vec tau, arma::vec caltimes, arma::vec gaptimes, arma::vec censored, arma::vec intercepts, arma::vec slopes, arma::vec lastperrep, arma::vec perrepind, arma::vec effagebegin, arma::vec effage, int ndiseff, arma::vec diseff, arma::mat cov, double alphaSeed, arma::vec betaSeed, double xi, arma::vec Z, arma::vec offset, int rhoFunc, double tol, int maxiter, int maxXi, arma::vec& estimEnd, arma::ivec& control, double& loglikEnd);
RcppExport SEXP _gcmrec_EstimWithFrailty(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP ndiseffSEXP, SEXP diseffSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP xiSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP maxXiSEXP, SEXP estimEndSEXP, SEXP controlSEXP, SEXP loglikEndSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< int >::type ndiseff(ndiseffSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type diseff(diseffSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type maxXi(maxXiSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type estimEnd(estimEndSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< double& >::type loglikEnd(loglikEndSEXP);
    EstimWithFrailty(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alphaSeed, betaSeed, xi, Z, offset, rhoFunc, tol, maxiter, maxXi, estimEnd, control, loglikEnd);
    return R_NilValue;
END_RCPP
}
// Jacknife
arma::mat Jacknife(double s, int n, int nvar, arma::ivec k, int nk, arma::vec tau, arma::vec caltimes, arma::vec gaptimes, arma::vec censored, arma::vec intercepts, arma::vec slopes, arma::vec lastperrep, arma::vec perrepind, arma::vec effagebegin, arma::vec effage, arma::mat cov, double alphaSeed, arma::vec betaSeed, arma::vec Z, arma::vec offset, int rhoFunc, arma::ivec ns, double tol, int maxiter);
RcppExport SEXP _gcmrec_Jacknife(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP nsSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(Jacknife(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// Jacknife2
arma::mat Jacknife2(double s, int n, int nvar, arma::ivec k, int nk, arma::vec tau, arma::vec caltimes, arma::vec gaptimes, arma::vec censored, arma::vec intercepts, arma::vec slopes, arma::vec lastperrep, arma::vec perrepind, arma::vec effagebegin, arma::vec effage, int ndiseff, arma::vec diseff, arma::mat cov, double alphaSeed, arma::vec betaSeed, double xi, arma::vec Z, arma::vec offset, int rhoFunc, double tol, int maxiter, int maxXi);
RcppExport SEXP _gcmrec_Jacknife2(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP ndiseffSEXP, SEXP diseffSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP xiSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP maxXiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< int >::type ndiseff(ndiseffSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type diseff(diseffSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type maxXi(maxXiSEXP);
    rcpp_result_gen = Rcpp::wrap(Jacknife2(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alphaSeed, betaSeed, xi, Z, offset, rhoFunc, tol, maxiter, maxXi));
    return rcpp_result_gen;
END_RCPP
}
// newtraph
void newtraph(double s, int n, int nvar, arma::ivec k, int nk, arma::vec tau, arma::vec caltimes, arma::vec gaptimes, arma::vec censored, arma::vec intercepts, arma::vec slopes, arma::vec lastperrep, arma::vec perrepind, arma::vec effagebegin, arma::vec effage, arma::mat cov, double alphaSeed, arma::vec betaSeed, arma::vec Z, arma::vec offset, int rhoFunc, arma::ivec ns, double tol, int maxiter, double& loglik, arma::vec& estiEnd, arma::mat& info, int& searchBoth, int& kkiter);
RcppExport SEXP _gcmrec_newtraph(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP nsSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP loglikSEXP, SEXP estiEndSEXP, SEXP infoSEXP, SEXP searchBothSEXP, SEXP kkiterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double& >::type loglik(loglikSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type estiEnd(estiEndSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type info(infoSEXP);
    Rcpp::traits::input_parameter< int& >::type searchBoth(searchBothSEXP);
    Rcpp::traits::input_parameter< int& >::type kkiter(kkiterSEXP);
    newtraph(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiEnd, info, searchBoth, kkiter);
    return R_NilValue;
END_RCPP
}
// newtraphBoth
void newtraphBoth(double s, int n, int nvar, arma::ivec k, int nk, arma::vec tau, arma::vec caltimes, arma::vec gaptimes, arma::vec censored, arma::vec intercepts, arma::vec slopes, arma::vec lastperrep, arma::vec perrepind, arma::vec effagebegin, arma::vec effage, arma::mat cov, double alphaSeed, arma::vec betaSeed, arma::vec Z, arma::vec offset, int rhoFunc, arma::ivec ns, double tol, int maxiter, double& loglik, arma::vec& estiNew, arma::mat& info, int& search, int& kiter);
RcppExport SEXP _gcmrec_newtraphBoth(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP nsSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP loglikSEXP, SEXP estiNewSEXP, SEXP infoSEXP, SEXP searchSEXP, SEXP kiterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double& >::type loglik(loglikSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type estiNew(estiNewSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type info(infoSEXP);
    Rcpp::traits::input_parameter< int& >::type search(searchSEXP);
    Rcpp::traits::input_parameter< int& >::type kiter(kiterSEXP);
    newtraphBoth(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiNew, info, search, kiter);
    return R_NilValue;
END_RCPP
}
// newtraphAlpha
void newtraphAlpha(double s, int n, int nvar, arma::ivec k, int nk, arma::vec tau, arma::vec caltimes, arma::vec gaptimes, arma::vec censored, arma::vec intercepts, arma::vec slopes, arma::vec lastperrep, arma::vec perrepind, arma::vec effagebegin, arma::vec effage, arma::mat cov, double alphaSeed, arma::vec betaSeed, arma::vec Z, arma::vec offset, int rhoFunc, arma::ivec ns, double tol, int maxiter, double& estiNew, int& search, int& kiter);
RcppExport SEXP _gcmrec_newtraphAlpha(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP nsSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP estiNewSEXP, SEXP searchSEXP, SEXP kiterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double& >::type estiNew(estiNewSEXP);
    Rcpp::traits::input_parameter< int& >::type search(searchSEXP);
    Rcpp::traits::input_parameter< int& >::type kiter(kiterSEXP);
    newtraphAlpha(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, estiNew, search, kiter);
    return R_NilValue;
END_RCPP
}
// newtraphBeta
void newtraphBeta(double s, int n, int nvar, arma::ivec k, int nk, arma::vec tau, arma::vec caltimes, arma::vec gaptimes, arma::vec censored, arma::vec intercepts, arma::vec slopes, arma::vec lastperrep, arma::vec perrepind, arma::vec effagebegin, arma::vec effage, arma::mat cov, double alphaSeed, arma::vec betaSeed, arma::vec Z, arma::vec offset, int rhoFunc, arma::ivec ns, double tol, int maxiter, arma::vec& estiNew, int& search, int& kiter);
RcppExport SEXP _gcmrec_newtraphBeta(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP nsSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP estiNewSEXP, SEXP searchSEXP, SEXP kiterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type estiNew(estiNewSEXP);
    Rcpp::traits::input_parameter< int& >::type search(searchSEXP);
    Rcpp::traits::input_parameter< int& >::type kiter(kiterSEXP);
    newtraphBeta(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, estiNew, search, kiter);
    return R_NilValue;
END_RCPP
}
// nrBeta
Rcpp::List nrBeta(double s, int n, int nvar, const arma::ivec& k, int nk, const arma::vec& tau, const arma::vec& caltimes, const arma::vec& gaptimes, const arma::vec& censored, const arma::vec& intercepts, const arma::vec& slopes, const arma::vec& lastperrep, const arma::vec& perrepind, const arma::vec& effagebegin, const arma::vec& effage, const arma::mat& cov, double alphaSeed, const arma::vec& betaSeed, const arma::vec& Z, const arma::vec& offset, int rhoFunc, const arma::ivec& ns, double tol, int maxiter, double& loglik, arma::vec& estiNew, arma::mat& infobeta, int& search, int& kiter);
RcppExport SEXP _gcmrec_nrBeta(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP nsSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP loglikSEXP, SEXP estiNewSEXP, SEXP infobetaSEXP, SEXP searchSEXP, SEXP kiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double& >::type loglik(loglikSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type estiNew(estiNewSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type infobeta(infobetaSEXP);
    Rcpp::traits::input_parameter< int& >::type search(searchSEXP);
    Rcpp::traits::input_parameter< int& >::type kiter(kiterSEXP);
    rcpp_result_gen = Rcpp::wrap(nrBeta(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiNew, infobeta, search, kiter));
    return rcpp_result_gen;
END_RCPP
}
// nrAlpha
Rcpp::List nrAlpha(double s, int n, int nvar, const arma::ivec& k, int nk, const arma::vec& tau, const arma::vec& caltimes, const arma::vec& gaptimes, const arma::vec& censored, const arma::vec& intercepts, const arma::vec& slopes, const arma::vec& lastperrep, const arma::vec& perrepind, const arma::vec& effagebegin, const arma::vec& effage, const arma::mat& cov, double alphaSeed, const arma::vec& betaSeed, const arma::vec& Z, const arma::vec& offset, int rhoFunc, const arma::ivec& ns, double tol, int maxiter, double& loglik, double& alphaNew, double& infoalpha, int& search, int& kiter);
RcppExport SEXP _gcmrec_nrAlpha(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP alphaSeedSEXP, SEXP betaSeedSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP nsSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP loglikSEXP, SEXP alphaNewSEXP, SEXP infoalphaSEXP, SEXP searchSEXP, SEXP kiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alphaSeed(alphaSeedSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type betaSeed(betaSeedSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double& >::type loglik(loglikSEXP);
    Rcpp::traits::input_parameter< double& >::type alphaNew(alphaNewSEXP);
    Rcpp::traits::input_parameter< double& >::type infoalpha(infoalphaSEXP);
    Rcpp::traits::input_parameter< int& >::type search(searchSEXP);
    Rcpp::traits::input_parameter< int& >::type kiter(kiterSEXP);
    rcpp_result_gen = Rcpp::wrap(nrAlpha(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, alphaNew, infoalpha, search, kiter));
    return rcpp_result_gen;
END_RCPP
}
// nsm
void nsm(double s, int n, int nk, const arma::vec& caltimes, const arma::ivec& k, arma::ivec& nm);
RcppExport SEXP _gcmrec_nsm(SEXP sSEXP, SEXP nSEXP, SEXP nkSEXP, SEXP caltimesSEXP, SEXP kSEXP, SEXP nmSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type nm(nmSEXP);
    nsm(s, n, nk, caltimes, k, nm);
    return R_NilValue;
END_RCPP
}
// scorefunc
void scorefunc(double s, int n, int nvar, arma::ivec k, int nk, arma::vec tau, arma::vec caltimes, arma::vec gaptimes, arma::vec censored, arma::vec intercepts, arma::vec slopes, arma::vec lastperrep, arma::vec perrepind, arma::vec effagebegin, arma::vec effage, arma::mat cov, double alpha, arma::vec beta, arma::vec Z, arma::vec offset, int rhoFunc, arma::ivec ns, double& loglik, arma::vec& score, arma::mat& info, double& scorealpha, arma::vec& scorebeta, double& infoalpha, arma::mat& infobeta);
RcppExport SEXP _gcmrec_scorefunc(SEXP sSEXP, SEXP nSEXP, SEXP nvarSEXP, SEXP kSEXP, SEXP nkSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP perrepindSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP ZSEXP, SEXP offsetSEXP, SEXP rhoFuncSEXP, SEXP nsSEXP, SEXP loglikSEXP, SEXP scoreSEXP, SEXP infoSEXP, SEXP scorealphaSEXP, SEXP scorebetaSEXP, SEXP infoalphaSEXP, SEXP infobetaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type perrepind(perrepindSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type rhoFunc(rhoFuncSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double& >::type loglik(loglikSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type info(infoSEXP);
    Rcpp::traits::input_parameter< double& >::type scorealpha(scorealphaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type scorebeta(scorebetaSEXP);
    Rcpp::traits::input_parameter< double& >::type infoalpha(infoalphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type infobeta(infobetaSEXP);
    scorefunc(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alpha, beta, Z, offset, rhoFunc, ns, loglik, score, info, scorealpha, scorebeta, infoalpha, infobeta);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gcmrec_EstLambSurv", (DL_FUNC) &_gcmrec_EstLambSurv, 26},
    {"_gcmrec_EstimWithFrailty", (DL_FUNC) &_gcmrec_EstimWithFrailty, 30},
    {"_gcmrec_Jacknife", (DL_FUNC) &_gcmrec_Jacknife, 24},
    {"_gcmrec_Jacknife2", (DL_FUNC) &_gcmrec_Jacknife2, 27},
    {"_gcmrec_newtraph", (DL_FUNC) &_gcmrec_newtraph, 29},
    {"_gcmrec_newtraphBoth", (DL_FUNC) &_gcmrec_newtraphBoth, 29},
    {"_gcmrec_newtraphAlpha", (DL_FUNC) &_gcmrec_newtraphAlpha, 27},
    {"_gcmrec_newtraphBeta", (DL_FUNC) &_gcmrec_newtraphBeta, 27},
    {"_gcmrec_nrBeta", (DL_FUNC) &_gcmrec_nrBeta, 29},
    {"_gcmrec_nrAlpha", (DL_FUNC) &_gcmrec_nrAlpha, 29},
    {"_gcmrec_nsm", (DL_FUNC) &_gcmrec_nsm, 6},
    {"_gcmrec_scorefunc", (DL_FUNC) &_gcmrec_scorefunc, 29},
    {NULL, NULL, 0}
};

RcppExport void R_init_gcmrec(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
