# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Non-parametric Hazard and Survival Estimation
#' @description Computes the baseline cumulative hazard (Nelson-Aalen) and 
#' survival (Kaplan-Meier) functions using the at-risk process.
#' @param s Current calendar time.
#' @param n Number of subjects.
#' @param nvar Number of covariates.
#' @param k Vector with number of observations per subject.
#' @param nk Total number of observations.
#' @param tau Truncation times.
#' @param caltimes Calendar times of events.
#' @param gaptimes Gap times between events.
#' @param censored Censoring indicators.
#' @param intercepts Covariate intercepts.
#' @param slopes Covariate slopes.
#' @param lastperrep Last periodic report time.
#' @param perrepind Periodic report indicator.
#' @param effagebegin Effective age at start.
#' @param effage Effective age at event.
#' @param ndiseff Number of unique event times.
#' @param diseff Sorted unique event times.
#' @param cov Covariate matrix.
#' @param alpha Alpha parameter (intensity scaling).
#' @param beta Beta coefficients vector.
#' @param Z Vector of frailties.
#' @param offset Offset vector.
#' @param rhoFunc Model type indicator.
#' @return A List containing lambdafunc, deltalambdafunc, and survfunc.
#' @export
EstLambSurv <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alpha, beta, Z, offset, rhoFunc, lambda, deltalambda, surv) {
    .Call('_gcmrec_EstLambSurv', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alpha, beta, Z, offset, rhoFunc, lambda, deltalambda, surv)
}

#' @title EM Algorithm for Frailty Models
#' @description Estimates parameters for a recurrent event model with gamma frailty.
#' @export
EstimWithFrailty <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alphaSeed, betaSeed, xi, Z, offset, rhoFunc, tol, maxiter, maxXi, estimEnd, control, loglikEnd) {
    invisible(.Call('_gcmrec_EstimWithFrailty', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alphaSeed, betaSeed, xi, Z, offset, rhoFunc, tol, maxiter, maxXi, estimEnd, control, loglikEnd))
}

#' @title Jacknife estimation (No Frailties)
#' @description Internal C++ function to perform Jackknife leave-one-out cross-validation for models without frailty.
#' @param s Scale parameter.
#' @param n Number of subjects.
#' @param nvar Number of covariates.
#' @param k Integer vector with the number of events per subject.
#' @param nk Total number of observations.
#' @param tau Vector of event/censoring times.
#' @param caltimes Vector of calendar times.
#' @param gaptimes Vector of gap times.
#' @param censored Censoring indicator vector.
#' @param intercepts Vector of intercepts for the effective age.
#' @param slopes Vector of slopes for the effective age.
#' @param lastperrep Vector of last perfect repair times.
#' @param perrepind Indicator of perfect repair.
#' @param effagebegin Effective age at the beginning of the interval.
#' @param effage Effective age at the end of the interval.
#' @param cov Matrix of covariates.
#' @param alphaSeed Initial value for alpha.
#' @param betaSeed Initial vector for betas.
#' @param Z Vector of frailty (fixed to 1 in this case).
#' @param offset Vector of offsets.
#' @param rhoFunc Integer indicating the type of rho function.
#' @param ns Integer vector for subjects (internal use).
#' @param tol Tolerance for convergence.
#' @param maxiter Maximum number of iterations.
#' @return A matrix of size (n x nvar+1) containing the parameter estimates for each jackknife iteration.
#' @export
Jacknife <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter) {
    .Call('_gcmrec_Jacknife', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter)
}

#' @title Jacknife estimation (With Frailties)
#' @description Internal C++ function to perform Jackknife leave-one-out cross-validation for models with frailty.
#' @param s Scale parameter.
#' @param n Number of subjects.
#' @param nvar Number of covariates.
#' @param k Integer vector with the number of events per subject.
#' @param nk Total number of observations.
#' @param tau Vector of event/censoring times.
#' @param caltimes Vector of calendar times.
#' @param gaptimes Vector of gap times.
#' @param censored Censoring indicator vector.
#' @param intercepts Vector of intercepts.
#' @param slopes Vector of slopes.
#' @param lastperrep Vector of last perfect repair times.
#' @param perrepind Indicator of perfect repair.
#' @param effagebegin Effective age start.
#' @param effage Effective age end.
#' @param ndiseff Number of distinct effective ages.
#' @param diseff Vector of distinct effective ages.
#' @param cov Matrix of covariates.
#' @param alphaSeed Initial alpha.
#' @param betaSeed Initial betas.
#' @param xi Initial xi (frailty variance).
#' @param Z Initial frailty vector.
#' @param offset Vector of offsets.
#' @param rhoFunc Type of rho function.
#' @param tol Tolerance.
#' @param maxiter Max iterations.
#' @param maxXi Optimization method for xi.
#' @return A matrix of size (n x nvar+2) containing parameter estimates (alpha, betas, xi) for each iteration.
#' @export
Jacknife2 <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alphaSeed, betaSeed, xi, Z, offset, rhoFunc, tol, maxiter, maxXi) {
    .Call('_gcmrec_Jacknife2', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, ndiseff, diseff, cov, alphaSeed, betaSeed, xi, Z, offset, rhoFunc, tol, maxiter, maxXi)
}

#' @title Master Newton-Raphson Optimizer
#' @description Coordinates the optimization process for the intensity parameters by alternating between Alpha and Beta.
#' @param s Current time point.
#' @param n Number of subjects.
#' @param nvar Number of covariates.
#' @param k Number of observations per subject.
#' @param nk Total number of observations across all subjects.
#' @param tau Vector of times.
#' @param caltimes Calendar times.
#' @param gaptimes Gap times.
#' @param censored Censoring indicator.
#' @param intercepts Intercepts for effective age.
#' @param slopes Slopes for effective age.
#' @param lastperrep Last perfect repair.
#' @param perrepind Perfect repair indicator.
#' @param effagebegin Effective age at start.
#' @param effage Effective age at end.
#' @param cov Matrix of covariates.
#' @param alphaSeed Initial value for alpha.
#' @param betaSeed Initial vector for betas.
#' @param Z Frailty vector.
#' @param offset Offset vector.
#' @param rhoFunc Type of rho function.
#' @param ns Internal subject vector.
#' @param tol Convergence tolerance.
#' @param maxiter Maximum number of iterations.
#' @param loglik Output: Final log-likelihood.
#' @param estiEnd Output: Vector of final estimates (alpha + betas).
#' @param info Output: Final information matrix.
#' @param searchBoth Output: Status of the final simultaneous optimization.
#' @param kkiter Output: Number of iterations performed.
#' @export
newtraph <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiEnd, info, searchBoth, kkiter) {
    invisible(.Call('_gcmrec_newtraph', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiEnd, info, searchBoth, kkiter))
}

#' @title Newton-Raphson for Alpha and Beta
#' @description Simultaneous optimization for alpha and beta parameters.
#' @keywords internal
#' @noRd
newtraphBoth <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiNew, info, search, kiter) {
    invisible(.Call('_gcmrec_newtraphBoth', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiNew, info, search, kiter))
}

#' @title Newton-Raphson for Alpha
#' @description Optimization restricted to the alpha parameter.
#' @keywords internal
#' @noRd
newtraphAlpha <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, estiNew, search, kiter) {
    invisible(.Call('_gcmrec_newtraphAlpha', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, estiNew, search, kiter))
}

#' @title Newton-Raphson for Beta
#' @description Optimization restricted to beta parameters.
#' @keywords internal
#' @noRd
newtraphBeta <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, estiNew, search, kiter) {
    invisible(.Call('_gcmrec_newtraphBeta', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, estiNew, search, kiter))
}

#' @title Newton-Raphson for Beta coefficients (Fixed Alpha)
#' @description Optimizes the beta vector using the information matrix.
#' @inheritParams Jacknife
#' @return A list with: loglik, estim (betas), info (infobeta), search, and kiter.
#' @export
nrBeta <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiNew, infobeta, search, kiter) {
    .Call('_gcmrec_nrBeta', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, estiNew, infobeta, search, kiter)
}

#' @title Newton-Raphson for Alpha (Fixed Betas)
#' @description Optimizes the alpha parameter (scalar) using the information.
#' @inheritParams Jacknife
#' @return A list with: loglik, alphaNew, infoalpha, search, and kiter.
#' @export
nrAlpha <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, alphaNew, infoalpha, search, kiter) {
    .Call('_gcmrec_nrAlpha', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alphaSeed, betaSeed, Z, offset, rhoFunc, ns, tol, maxiter, loglik, alphaNew, infoalpha, search, kiter)
}

#' @title Count Events per Subject (nsm)
#' @description Master routine to fill the event count vector for all subjects.
#' @param s Current evaluation time.
#' @param n Number of subjects.
#' @param nk Total number of observations in caltimes.
#' @param caltimes Global vector of calendar times.
#' @param k Vector with the number of observations for each subject.
#' @param nm [Out] Vector to store the results (integer).
#' @export
nsm <- function(s, n, nk, caltimes, k, nm) {
    invisible(.Call('_gcmrec_nsm', PACKAGE = 'gcmrec', s, n, nk, caltimes, k, nm))
}

#' @title Likelihood and Score Calculation
#' @description Computes the log-likelihood, score vector, and information matrix 
#' for a given set of parameters in a recurrent event model.
#' @param s Current time point.
#' @param n Number of subjects.
#' @param nvar Number of covariates.
#' @param k Observations per subject.
#' @param nk Total number of observations.
#' @param tau Censoring times.
#' @param caltimes Calendar times.
#' @param gaptimes Gap times.
#' @param censored Censoring indicators.
#' @param intercepts Model intercepts.
#' @param slopes Model slopes.
#' @param lastperrep Periodic report indices.
#' @param perrepind Periodic report indicators.
#' @param effagebegin Effective age starts.
#' @param effage Effective age ends.
#' @param cov Covariate matrix.
#' @param alpha Recurrence parameter.
#' @param beta Regression coefficients.
#' @param Z Fragility/Random effect vector.
#' @param offset Offsets vector.
#' @param rhoFunc Type of rho function.
#' @param ns Vector of event counts per subject.
#' @param loglik [Out] Computed log-likelihood.
#' @param score [Out] Full score vector (alpha + beta).
#' @param info [Out] Full information matrix.
#' @param scorealpha [Out] Score component for alpha.
#' @param scorebeta [Out] Score component for beta.
#' @param infoalpha [Out] Information component for alpha.
#' @param infobeta [Out] Information matrix for beta.
#' @export
scorefunc <- function(s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alpha, beta, Z, offset, rhoFunc, ns, loglik, score, info, scorealpha, scorebeta, infoalpha, infobeta) {
    invisible(.Call('_gcmrec_scorefunc', PACKAGE = 'gcmrec', s, n, nvar, k, nk, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, perrepind, effagebegin, effage, cov, alpha, beta, Z, offset, rhoFunc, ns, loglik, score, info, scorealpha, scorebeta, infoalpha, infobeta))
}

